### ISSUE TITLE
Размер кода и производительность

### ISSUE THREAD

**Issue by XRay3D** [GyverLibs/GSON#1]
https://github.com/GyverLibs/GSON/blob/7a87b99397f95ea604a85326534d9d3fe6feff50/src/utils/bson.h#L313C1-L322C10

Это по идее быстрее и меньше по флэшу.

https://godbolt.org/z/TsYrPGa7n

```cpp
uint8_t fl{};
if (3 [(uint8_t*)&val]) fl = 4;
if (2 [(uint8_t*)&val]) fl = 3;
if (1 [(uint8_t*)&val]) fl = 2;
if (0 [(uint8_t*)&val]) fl = 1;
return fl;
```

**Comment by XRay3D** [comment]
А так, в общем, решил весь код прошерстить)))
Хотя Xtensa gcc почти одинаковый выхлоп даёт.

**Comment by GyverLibs** [comment]
чуть быстрее, но работает вообще неправильно

**Comment by XRay3D** [comment]
> чуть быстрее, но работает вообще неправильно

Что-то протупил, пора спать похоже.
Первоначально правильно всё было. https://godbolt.org/z/vKr4M8eKb

**Comment by GyverLibs** [comment]
всё ещё неправильно) 0 это 1 байт должен быть

**Comment by GyverLibs** [comment]
вот в таком виде можно добавить да
```cpp
uint8_t _uintSize2(uint32_t val) {
  if (((uint8_t*)&val)[3]) return 4;
  if (((uint8_t*)&val)[2]) return 3;
  if (((uint8_t*)&val)[1]) return 2;
  return 1;
}
```

**Comment by GyverLibs** [comment]
хотя, в текущей реализации на js будет работать и с нулём, то есть если нулевой инт вообще не прибавятся к пакету. Надо тестировать

**Comment by GyverLibs** [comment]
да, работает с нулём, спасибо за идею)

**Comment by XRay3D** [comment]
> вот в таком виде можно добавить да
> 
> ```c++
> uint8_t _uintSize2(uint32_t val) {
>   if (((uint8_t*)&val)[3]) return 4;
>   if (((uint8_t*)&val)[2]) return 3;
>   if (((uint8_t*)&val)[1]) return 2;
>   return 1;
> }
> ```
Глубоко не копал вчера и ноль оставил.
Я в примере сэкономил пару скобок, выглядит, конечно, забавно)) Си и кресты умеют в мозговыносный синтаксис))) Я так понял, отрицательные числа обрабатываются иначе.

**Comment by GyverLibs** [comment]
Забавно, но лучше так не писать, больше похоже на косяк в языке. Такой же как возможность передать кучу аргументов в функцию без аргументов в си)) отрицательные берутся с обратным знаком
