### ISSUE TITLE
не получается добавить массив

### ISSUE THREAD

**Issue by ingenerVK** [GyverLibs/GSON#2]
#include <GSON.h>
gson::string gs; 
gs.beginArr("statuseSwitch");

Compiling .pio\build\lolin32_lite\src\main.cpp.o
src/main.cpp:16:1: error: 'gs' does not name a type
 gs.beginArr("statuseSwitch");
 ^~
*** [.pio\build\lolin32_lite\src\main.cpp.o] Error 1

**Comment by GyverLibs** [comment]
![image](https://github.com/user-attachments/assets/64af2085-53aa-431f-bcee-f3e3e423cc01)
